import 'package:flutter/material.dart';

class ColorConstants {
  static const Color alabaster = Color(0xFFF8F8F8);
  static const Color alto = Color(0xFFD9D9D9);
  static const Color black = Colors.black;
  static const Color black30 = Color(0xFF6B6B6B);
  static const Color blue = Color(0xFF3F95F8);
  static const Color concrete = Color(0xFFF3F3F3);
  static const Color downPink = Color(0xFFEBEBEB);
  static const Color dullWhite = Color(0xFFF2F6F9);
  static const Color gallery = Color(0xFFEEEEEE);
  static const Color green = Color(0xFF53A55B);
  static const Color grey = Color(0xFF394652);
  static const Color shadedGrey = Color(0xFFB8B8B8);
  static const Color laPalma = Color(0xFF2F9417);
  static const Color lightGrey = Color(0xFFF6F6F6);
  static const Color mercury = Color(0xFFE2E2E2);
  static const Color milanoRed = Color(0xFFBF0E0E);
  static const Color purple = Color(0xFF7444F4);
  static const Color pippin = Color(0xFFFFE4E7);
  static const Color radicalRed = Color(0xFFF9415A);
  static const Color semiGrey = Color(0xFFB1B1B1);
  static const Color shark = Color(0xFF252526);
  static const Color shuttleGray = Color(0xFF616A78);
  static const Color silverChalice = Color(0xFFA2A2A2);
  static const Color dustyGray = Color(0xFF949494);
  static const Color boulder = Color(0xFF7C7C7C);
  static const Color transparent = Colors.transparent;
  static const Color white = Colors.white;
  static const Color apple = Color(0xFF60A830);
  static const Color mineShaft = Color(0xFF363636);
  static const Color woodSmoke = Color(0xFF0E0E10);
  static const Color mischka = Color(0xFFDFE1E6);
  static const Color hintGreen = Color(0xffECFFEE);
  static const Color lightGre = Color(0xff363636);
  static const Color dodgerBlue = Color(0xff2D80FC);
  static const Color dustyGrey = Color(0xff9A9A9A);
  static const Color biscay = Color(0xff1E4B6E);
  static const Color persianRed  = Color(0xffCE2828);
  static const Color ebony = Color(0xFF070C18);
  static const Color ebonyClay = Color(0xFF1C2229);
  static const Color regentGray = Color(0xFF8890A0);
  static const Color funBlue = Color(0xFF1561A9);
  static const Color ceriseRed= Color(0xFFDB354F);
  static const Color toryBlue= Color(0xFF0F62AC);
  static const Color amaranth= Color(0xFFEE3147);
}
